@startuml packages
set namespaceSeparator none
package "PGLEventManagerController" as PGLEventManagerController
package "PGLEventManagerMain" as PGLEventManagerMain
package "PGLEventManagerModel" as PGLEventManagerModel
PGLEventManagerController --> PGLEventManagerModel
PGLEventManagerMain *--> PGLEventManagerController
PGLEventManagerMain *--> PGLEventManagerModel
@enduml
