@startuml packages
set namespaceSeparator none
package "src" as src {
}
package "src.PGLEventManagerController" as src.PGLEventManagerController {
}
package "src.PGLEventManagerMain" as src.PGLEventManagerMain {
}
package "src.PGLEventManagerModel" as src.PGLEventManagerModel {
}
src.PGLEventManagerController --> src.PGLEventManagerModel
src.PGLEventManagerMain --> src.PGLEventManagerController
src.PGLEventManagerMain --> src.PGLEventManagerModel
@enduml
